spring.application.name=seminar-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/database
spring.datasource.username=srebrenko
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
